title: "AbjadStyleTransfer"
#description: "Call for Participation: AraGenEval"
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: "https://forms.gle/JYYMFMWqufdTHmxa6"
  repository_name: "Registration Open"
markdown:
  kramdown:
    auto_ids: false  # This disables automatic heading IDs

